### ISSUE TITLE
New iSSUE

### ISSUE THREAD

**Issue by Pigeons** [danrmiller/thisisatest#9]
New Issue from a user not on the ACL

#new

**Comment by issue-helper** [comment]
**What's next?** A reviewer should examine this issue.

**Comment by Pigeons** [comment]
#new

**Comment by danrmiller** [comment]
+resolved

**Comment by issue-helper** [comment]
**Label:** resolved.

**Comment by issue-helper** [comment]
**Label:** resolved.

**Comment by issue-helper** [comment]
**Label:** resolved.
